-- OLTP процессинга карт. Сюда пишет генератор и симулятор, отсюда читают
-- начальная выгрузка (JDBC) и Debezium (логическая репликация).

create schema if not exists core;

create table if not exists core.clients (
    client_id    bigint primary key,
    full_name    text        not null,
    birth_date   date        not null,
    phone        text,
    email        text,
    city         text        not null,
    segment      text        not null check (segment in ('mass', 'affluent', 'private')),
    created_at   timestamptz not null,
    updated_at   timestamptz not null,
    row_version  bigint      not null default 1
);

create table if not exists core.accounts (
    account_id   bigint primary key,
    client_id    bigint      not null references core.clients,
    currency     char(3)     not null,
    status       text        not null check (status in ('open', 'closed')),
    opened_at    timestamptz not null,
    closed_at    timestamptz,
    updated_at   timestamptz not null,
    row_version  bigint      not null default 1
);

create table if not exists core.cards (
    card_id      bigint primary key,
    account_id   bigint      not null references core.accounts,
    pan_masked   text        not null,
    product      text        not null check (product in ('classic', 'gold', 'platinum', 'business')),
    status       text        not null check (status in ('active', 'blocked', 'expired')),
    issued_at    timestamptz not null,
    expires_at   date        not null,
    updated_at   timestamptz not null,
    row_version  bigint      not null default 1
);

create table if not exists core.merchants (
    merchant_id  bigint primary key,
    name         text        not null,
    mcc          char(4)     not null,
    city         text        not null,
    country      char(2)     not null,
    updated_at   timestamptz not null,
    row_version  bigint      not null default 1
);

create table if not exists core.card_transactions (
    txn_id       bigint generated by default as identity primary key,
    card_id      bigint         not null,
    merchant_id  bigint         not null,
    txn_ts       timestamptz    not null,
    amount       numeric(14, 2) not null,
    currency     char(3)        not null,
    status       text           not null check (status in ('authorized', 'posted', 'reversed')),
    auth_code    char(6)        not null,
    created_at   timestamptz    not null,
    updated_at   timestamptz    not null,
    row_version  bigint         not null default 1
);

create table if not exists core.fx_rates (
    rate_date    date           not null,
    currency     char(3)        not null,
    rate_kzt     numeric(12, 4) not null,
    updated_at   timestamptz    not null,
    row_version  bigint         not null default 1,
    primary key (rate_date, currency)
);

-- Версия строки растёт на каждом UPDATE. По ней ods решает, какое из двух
-- состояний строки новее, когда одно пришло из начальной выгрузки, а другое из CDC.
create or replace function core.bump_row_version() returns trigger
language plpgsql as $$
begin
    new.row_version := old.row_version + 1;
    new.updated_at  := now();
    return new;
end $$;

do $$
declare t text;
begin
    foreach t in array array['clients', 'accounts', 'cards', 'merchants', 'card_transactions', 'fx_rates'] loop
        execute format('drop trigger if exists bump_row_version on core.%I', t);
        execute format('create trigger bump_row_version before update on core.%I
                        for each row execute function core.bump_row_version()', t);
        -- в событии удаления нужна вся строка, иначе там только первичный ключ и не будет версии
        execute format('alter table core.%I replica identity full', t);
    end loop;
end $$;

-- для симулятора: найти авторизации, которые пора подтвердить или снять
create index if not exists card_transactions_status_ts
    on core.card_transactions (status, txn_ts) where status = 'authorized';

-- публикация для Debezium создаётся заранее и явно: у пользователя cdc нет прав
-- создавать публикации на все таблицы
drop publication if exists cdc_core;
create publication cdc_core for table
    core.clients, core.accounts, core.cards, core.merchants, core.card_transactions, core.fx_rates;

do $$
begin
    if not exists (select from pg_roles where rolname = 'cdc') then
        create role cdc with login replication password 'cdc';
    end if;
end $$;
grant usage on schema core to cdc;
grant select on all tables in schema core to cdc;
